### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by TheDelus** [gavanderhoorn/industrial_robot_status_controller#5]
Is a noetic release planned for this package?

**Comment by gavanderhoorn** [comment]
Plans? Yes.

But we're currently blocked by `industrial_core`, which itself is blocked.

See http://repositories.ros.org/status_page/blocked_source_entries_noetic.html?q=id%3D%22industrial_core%22&s=6&r=1.

**Comment by gavanderhoorn** [comment]
Has been released: [status_page/ros_noetic_default.html?q=industrial_robot_status](http://repositories.ros.org/status_page/ros_noetic_default.html?q=industrial_robot_status).
